#!/bin/sh

case "$1" in
  purge)
    if [ -f /opt/Ombi/Ombi.db ]; then
      rm -f /opt/Ombi/Ombi.db
    fi
    if [ -f /opt/Ombi/Schedules.db ]; then
      rm -f /opt/Ombi/Schedules.db
    fi
    if [ -d /opt/Ombi/Logs ]; then
      rm -rf /opt/Ombi/Logs
    fi
  ;;

  remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    # Do nothing extra
  ;;

  *)
    echo "postrm called with unknown argument \`$1'" >&2
    exit 1
  ;;

esac

#DEBHELPER#

exit 0
